---
services:
  audiobooks-tailscale:
    image: tailscale/tailscale:latest
    hostname: audiobooks
    environment:
      - TS_HOSTNAME=audiobooks
      # - TS_STATE_DIR=/var/run/tailscale
      - TS_STATE_DIR=${DATA_DIR}/audiobookshelf/tailscale
      - TS_AUTHKEY=${AUDIOBOOKSHELF_KEY}
      # - TS_USERSPACE=false
    volumes:
      - ${DATA_DIR}/audiobookshelf/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/audiobookshelf/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun           # Required for tailscale to work
    ports:
      - 8081:80
    cap_add:       # Required for tailscale to work
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    volumes:
      - ${DATA_DIR}/audiobookshelf/Audiobooks:/audiobooks
      - ${DATA_DIR}/audiobookshelf/Podcasts:/podcasts
      - ${DATA_DIR}/audiobookshelf/config:/config
      - ${DATA_DIR}/audiobookshelf/metadata:/metadata
    depends_on:
      audiobooks-tailscale:
        condition: service_healthy
    network_mode: service:audiobooks-tailscale

volumes:
  audiobookshelf:
  tailscale:
  tls:
