---
version: "3.7"
services:
  tailscale:
    hostname: docker-books             # This will become the tailscale device name
    image: tailscale/tailscale
    volumes:
      - DATA-DIR/audiobookshelf/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
    cap_add:                                    # Required for tailscale to work
      - net_admin
      - sys_module
    environment:
      - TS_AUTHKEY=AUDIOBOOKSHELF-KEY
      - TS_USERSPACE=true
    # command: tailscaled
    healthcheck:
      test: "exit 0"

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    network_mode: service:tailscale
    volumes:
      - DATA-DIR/audiobookshelf/Audiobooks:/audiobooks
      - DATA-DIR/audiobookshelf/Podcasts:/podcasts
      - DATA-DIR/audiobookshelf/config:/config
      - DATA-DIR/audiobookshelf/metadata>:/metadata
    depends_on:
      tailscale:
        condition: service_healthy
