---
services:
  ts-fenrus:
    image: tailscale/tailscale:latest
    hostname: fenrus
    environment:
      - TS_HOSTNAME=fenrus
      - TS_STATE_DIR=${DATA_DIR}/fenrus/tailscale
      - TS_AUTHKEY=${FENRUS_KEY}
      # - TS_USERSPACE=false
    volumes:
      - ${DATA_DIR}/fenrus/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/fenrus/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun           # Required for tailscale to work
    ports:
      - 3000:3000
    cap_add:       # Required for tailscale to work
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  fenrus:
    image: revenz/fenrus
    container_name: fenrus
    environment:
      - TZ=${HOME_TIMEZONE}
    volumes:
      - ${DATA_DIR}/fenrus/data:/app/data
    depends_on:
      ts-fenrus:
        condition: service_healthy
    network_mode: service:ts-fenrus
    restart: unless-stopped

volumes:
  fenrus:
  tailscale:
  tls:
