---
version: "3.8"
services:
  ts-hoarder:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/hoarder/tailscale:/var/lib/tailscale
      - ${DATA_DIR}/hoarder/tailscale/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_HOSTNAME=hoarder
      - TS_STATE_DIR=${DATA_DIR}/hoarder/tailscale
      # - TS_USERSPACE=true
      - TS_AUTHKEY=${HOARDER_KEY}
    ports:
      - 3001:3000
      - 9222:9222
      - 7700:7700
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - ${DATA_DIR}/hoarder/data:/data
    # ports:
    #   - 3000:3000
    network_mode: service:ts-monica
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ${DATA_DIR}/hoarder/meilisearch:/meili_data

volumes:
  meilisearch:
  data:
