---
# version: "3"
version: "3.7"

services:
  docker-keycloak:
    image: tailscale/tailscale:stable
    hostname: docker-keycloak             # This will become the tailscale device name
    # network_mode: "host"
    environment:
      - TS_AUTHKEY=<YOUR TAILSCALE AUTH KEY HERE>
      - TS_USERSPACE=true
    volumes:
      - ./tailscale/state:/var/lib/tailscale        # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun           # Required for tailscale to work
    cap_add:                                    # Required for tailscale to work
      - net_admin
      - sys_module
    ports:
      - 8080:8080
      - 5432:5432
    # command: tailscaled
    healthcheck:
      test: "exit 0"

  postgres:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: "exit 0"
    # ports:
    #   - 5432:5432
    network_mode: service:docker-keycloak
    # networks:
    #   - keycloak_network
    depends_on:
      docker-keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    environment:
      KC_DB: postgres
      # KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: 123456
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: docker-keycloak.<YOUR TAILSCALE DNS>
    # ports:
    #   - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: service:docker-keycloak
    # networks:
      # - keycloak_network

networks: {}
#   keycloak_network:
#     driver: bridge

# volumes:
#   postgres_data:
#     driver: local
