---
services:
  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/keycloak/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/keycloak/tls:/mnt/tls
    environment:
      - TS_HOSTNAME=keycloak
      - TS_STATE_DIR=${DATA_DIR}/keycloak/tailscale  #/var/run/tailscale
    ports:
      - 80:8080
      - 5432:5432
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  postgres:
    image: postgres:17
    volumes:
      - ${DATA_DIR}/keycloak/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      # KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_USERNAME: ${KEYCLOAK_USERNAME}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # KC_HOSTNAME: keycloak.${TS_DOMAIN}
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: service:tailscale

volumes:
  tailscale:
  tls:
  postgres:
  keycloak:
