---
# version: "3"
# version: "3.7"

services:
  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ../data/keycloak/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ../data/keycloak/tls:/mnt/tls
    environment:
      - TS_HOSTNAME=keycloak
      - TS_STATE_DIR=../data/keycloak/tailscale  #/var/run/tailscale
    ports:
      - 80:8080
      - 5432:5432
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  postgres:
    image: postgres:17
    volumes:
      - ../data/keycloak/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: "exit 0"
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      # KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: 123456
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      # KC_HOSTNAME: keycloak.tail0301a.ts.net # TAILSCALE-DNS
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: service:tailscale

volumes:
  tailscale:
  tls:
  postgres:
  keycloak:
