services:
  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ../data/nextcloud/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ../data/nextcloud/tls:/mnt/tls
    environment:
      TS_HOSTNAME: nextcloud
      TS_STATE_DIR: ../data/nextcloud/tailscale  #/var/run/tailscale
      TS_AUTHKEY: ${nextcloud_key}
    ports:
      # - 80:80
      - 8080:8080
      - 5432:5432
    # healthcheck:
    #   test: "exit 0"
    env_file: .env
    restart: always

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - ../data/nextcloud/db:/var/lib/postgresql/data
    network_mode: service:tailscale
    environment:
      POSTGRES_DB: ${NextcloudUser}
      POSTGRES_PASSWORD: ${NextcloudPassword}
      POSTGRES_USER: ${NextcloudUser}
    env_file: .env
    # depends_on:
    #   tailscale:
    #     condition: service_healthy

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
    # depends_on:
    #   tailscale:
    #     condition: service_healthy

  app:
    image: nextcloud:30
    restart: unless-stopped
    network_mode: service:tailscale
    hostname: "nextcloud"
    container_name: "nextcloud"
    env_file: .env
    depends_on:
      # - redis
      - db
      - tailscale
    volumes:
      - ../data/nextcloud:/var/www/html
    environment:
      POSTGRES_PASSWORD: ${NextcloudPassword}
      POSTGRES_DATABASE: ${NextcloudPassword}
      POSTGRES_USER: ${NextcloudUser}
      POSTGRES_HOST: db
# volumes:
#   nextcloud:
#   db:
#   tailscale:
