services:
  nextcloud-tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/nextcloud/tailscale:/var/lib/tailscale
      - ${DATA_DIR}/nextcloud/tailscale/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}/nextcloud/var/run/tailscale:/var/run/tailscale
    environment:
      - TS_HOSTNAME=nextcloud
      - TS_STATE_DIR=${DATA_DIR}/nextcloud/tailscale  #/var/run/tailscale
      # - TS_USERSPACE=true
      - TS_AUTHKEY=${NEXTCLOUD_KEY}
    ports:
      - 80:80
      # - 8080:8080
      # - 8443:8443
      - 443:443
      # - 5432:5432
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  db:
    image: postgres:17
    restart: always
    # network_mode: service:nextcloud-tailscale
    volumes:
      - ${DATA_DIR}/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    healthcheck:
      test: "exit 0"

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:30
    restart: always
    network_mode: service:nextcloud-tailscale
    volumes:
      - ${DATA_DIR}/nextcloud:/var/www/html
      - ${DATA_DIR}/nextcloud/data:/var/www/html/data
      - ${DATA_DIR}/nextcloud/config:/var/www/html/config
      - ${DATA_DIR}/nextcloud/apps:/var/www/html/apps
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}

      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${TS_DOMAIN}
      - NEXTCLOUD_UPLOAD_LIMIT="10G"
      - NEXTCLOUD_MAX_TIME="3600"
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true
      - NEXTCLOUD_KEEP_DISABLED_APPS=false

      - REDIS_HOST=redis
    depends_on:
      - redis
      - db
      - tailscale

volumes:
  db:
  nextcloud:
  tailscale:
  tls:
