version: "2.3"
# ---
services:
  ts-ntfy:
    image: tailscale/tailscale:latest
    hostname: ntfy
    environment:
      - TS_HOSTNAME=ntfy
      # - TS_STATE_DIR=/var/run/tailscale
      - TS_STATE_DIR=${DATA_DIR}/ntfy/tailscale
      - TS_AUTHKEY=${NTFY_KEY}
      # - TS_USERSPACE=false
    volumes:
      - ${DATA_DIR}/ntfy/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/ntfy/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun           # Required for tailscale to work
    ports:
      - 8083:80
    cap_add:       # Required for tailscale to work
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${HOME_TIMEZONE}    # optional: set desired timezone
    user: 1000:1000 # optional: replace with your own user/group or uid/gid
    volumes:
      - ${DATA_DIR}/ntfy:/var/cache/ntfy
      - ${DATA_DIR}/ntfy:/etc/ntfy
    network_mode: service:ts-ntfy
    # ports:
    #   - 8083:80

    # healthcheck: # optional: remember to adapt the host:port to your environment
    #     test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
    #     interval: 60s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 40s
    depends_on:
      ts-ntfy:
        condition: service_healthy
    restart: unless-stopped
