---
services:

  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/nextcloud/tailscale:/var/lib/tailscale
      - ${DATA_DIR}/nextcloud/tailscale/tls:/mnt/tls
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TS_HOSTNAME=nextcloud
      - TS_STATE_DIR=${DATA_DIR}/nextcloud/tailscale  #/var/run/tailscale
      # - TS_USERSPACE=false
      - TS_AUTHKEY=${PINCHFLAT_KEY}
    ports:
      - '8945:8945'
    restart: unless-stopped

  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      - TZ=America/New_York
    network_mode: service:tailscale
    # ports:
    #   - '8945:8945'
    volumes:
      - ${DATA_DIR}/pinchflat/config:/config
      - ${DATA_DIR}/pinchflat/downloads:/downloads
