---
services:
  ts-pinchflat:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/pinchflat/tailscale:/var/lib/tailscale
      - ${DATA_DIR}/pinchflat/tailscale/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_HOSTNAME=pinchflat
      - TS_STATE_DIR=${DATA_DIR}/pinchflat/tailscale  #/var/run/tailscale
      # - TS_USERSPACE=true
      - TS_AUTHKEY=${PINCHFLAT_KEY}
    ports:
      - 8945:8945
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      - TZ=${HOME_TIMEZONE}
    network_mode: service:tailscale
    # ports:
    #   - '8945:8945'
    volumes:
      - ${DATA_DIR}/pinchflat/config:/config
      - ${MEDIA_DIR}/webshows:/downloads
    depends_on:
      - ts-pinchflat
