---
services:
  searxng-tailscale:
    image: tailscale/tailscale:latest
    # hostname: searxng
    environment:
      - TS_HOSTNAME=searxng
      - TS_STATE_DIR=${DATA_DIR}/searxng/tailscale
      # - TS_STATE_DIR=/var/run/tailscale
      - TS_AUTHKEY=${SEARXNG_TS_KEY}
      - TS_USERSPACE=false
      # - TS_SERVE_CONFIG=/config/searxng.json
      - TS_SERVE_CONFIG=${DATA_DIR}/searxng/config/searxng.json
    volumes:
      - ${DATA_DIR}/searxng/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/searxng/tls:/mnt/tls
      - ${DATA_DIR}/searxng/config:/config
      - /dev/net/tun:/dev/net/tun           # Required for tailscale to work
    # devices:
      # - /dev/net/tun:/dev/net/tun
    ports:
      - "8180:8080"
    cap_add:      # Required for tailscale to work
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    network_mode: service:searxng-tailscale
    volumes:
      - ${DATA_DIR}/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://searxng.${TS_DOMAIN}
      # - PGID=977
      # - PUID=977
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - searxng-tailscale
      # - redis

  # redis:
  #   container_name: redis
  #   image: docker.io/valkey/valkey:8-alpine
  #   command: valkey-server --save 30 1 --loglevel warning
  #   restart: unless-stopped
  #   volumes:
  #     - ${DATA_DIR}/searxng/valkey-data2:/data
  #   # environment:
  #   #   - PGID=977
  #   #   - PUID=977
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - SETGID
  #     - SETUID
  #     - DAC_OVERRIDE
  #   network_mode: service:searxng-tailscale
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1m"
  #       max-file: "1"


volumes:
  tailscale:
  tls:
  # valkey-data2:
  searxng:
