services:
  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ../data/searxng/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ../data/searxng/tls:/mnt/tls
    environment:
      - TS_HOSTNAME=searxng
      - TS_STATE_DIR=../data/searxng/tailscale  #/var/run/tailscale
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      tailscale:
        condition: service_healthy
    healthcheck:
      test: "exit 0"


  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - ./data/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      # - SETGID
      # - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      tailscale:
      # redis:
        condition: service_healthy

volumes:
  tailscale:
  tls:
  valkey-data2:
