services:
  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/searxng/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/searxng/tls:/mnt/tls
    environment:
      TS_HOSTNAME: "searxng"
      TS_STATE_DIR: ${DATA_DIR}/searxng/tailscale  #/var/run/tailscale
      TS_AUTHKEY: ${SEARXNG_TS_KEY}
    ports:
      # - "8080:8080"
      - "80:8080"
      # - "127.0.0.1:8080:8080"
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - ${DATA_DIR}/searxng/valkey-data2:/data
    environment:
      - PGID=977
      - PUID=977
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      tailscale:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - ${DATA_DIR}/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL="http://searxng.${TS_DOMAIN}"
      # - UWSGI_WORKERS=4
      # - UWSGI_THREADS=4
      - PGID=977
      - PUID=977
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      tailscale:
      # redis:
        condition: service_healthy

volumes:
  tailscale:
  tls:
  valkey-data2:
  searxng:
