# Docker compose for development purposes only.
# Edit it to fit your current development needs.
---
services:
  ts-shiori:
    image: tailscale/tailscale:latest
    volumes:
      - ${DATA_DIR}/shiori/tailscale:/var/lib/tailscale
      - ${DATA_DIR}/shiori/tailscale/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_HOSTNAME=shiori
      - TS_STATE_DIR=${DATA_DIR}/shiori/tailscale
      # - TS_USERSPACE=true
      - TS_AUTHKEY=${SHIORI_KEY}
    ports:
      - 8086:8080
      - 8087:8081
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  shiori:
    build:
      context: .
      dockerfile: Dockerfile.compose
    container_name: shiori
    command:
      - "server"
      - "--log-level"
      - "debug"
    network_mode: service:ts-shiori
    # ports:
    #   - "8080:8080"
    volumes:
      - "${DATA_DIR}/shiori/dev-data:/srv/shiori"
      - "${DATA_DIR}/shiori:/src/shiori"
      - "go-mod-cache:/go/pkg/mod"
    restart: unless-stopped
    links:
      - "postgres"
      - "mariadb"
    environment:
      SHIORI_DIR: /srv/shiori
      # SHIORI_HTTP_ROOT_PATH: /shiori/
      # SHIORI_DATABASE_URL: mysql://shiori:shiori@(mariadb)/shiori?charset=utf8mb4
      # SHIORI_DATABASE_URL: postgres://shiori:shiori@postgres/shiori?sslmode=disable

  nginx:
    image: nginx:alpine
    network_mode: service:ts-shiori
    # ports:
    #   - "8087:8081"
    volumes:
      - "${DATA_DIR}/shiori/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - shiori

  postgres:
    image: postgres:13.18
    environment:
      POSTGRES_PASSWORD: shiori
      POSTGRES_USER: shiori
    ports:
      - "5432:5432"

  mariadb:
    image: mariadb:10.5.27
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shiori
      MYSQL_USER: shiori
      MYSQL_PASSWORD: shiori
    ports:
      - "3306:3306"

  mysql:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shiori
      MYSQL_USER: shiori
      MYSQL_PASSWORD: shiori
    ports:
      - "3307:3306"

volumes:
  go-mod-cache:
