---
services:
  ts-tubearchivist:
    image: tailscale/tailscale:latest
    environment:
      - TS_HOSTNAME=tubearchivist
      - TS_STATE_DIR=${DATA_DIR}/tubearchivist/tailscale  #/var/run/tailscale
      - TS_AUTHKEY=${TUBEARCHIVIST_KEY}
    volumes:
      - ${DATA_DIR}/tubearchivist/tailscale:/var/lib/tailscale        # State data will be stored in this directory
      - ${DATA_DIR}/tubearchivist/tls:/mnt/tls
      - /dev/net/tun:/dev/net/tun           # Required for tailscale to work
    ports:
      - 8000:8000
      # - 6379:6379
      # - 9200:9200
    cap_add:                                    # Required for tailscale to work
      - net_admin
      - sys_module
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    network_mode: service:ts-tubearchivist
    # ports:
    #   - 8000:8000
    volumes:
      - ${DATA_DIR}/tubearchivist/media:/youtube
      - ${DATA_DIR}/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://tubearchivist.${TS_DOMAIN}:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.${TS_DOMAIN}        # set your host name
      - TA_USERNAME=${TUBE_USER}                  # your initial TA credentials
      - TA_PASSWORD=${TUBE_PASSWORD}              # your initial TA credentials
      - ELASTIC_PASSWORD=${TUBE_ELASTIC_PASSWORD} # set password for Elasticsearch
      - TZ=${HOME_TIMEZONE}                       # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://tubearchivist.${TS_DOMAIN}:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    network_mode: service:ts-tubearchivist
    environment:
      - HOST_UID=1000
      - HOST_GID=1000
    # expose:
    #   - "6379"
    volumes:
      - ${DATA_DIR}/tubearchivist/redis:/data
    healthcheck:
      test: "exit 0"
    depends_on:
      archivist-es:
        condition: service_healthy

  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.14.3
    container_name: archivist-es
    restart: unless-stopped
    network_mode: service:ts-tubearchivist
    # expose:
    #   - "9200"
    environment:
      - "ELASTIC_PASSWORD=${TUBE_ELASTIC_PASSWORD}"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      # - "path.repo=/usr/share/elasticsearch/data/snapshot"
      - HOST_UID=1000
      - HOST_GID=1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DATA_DIR}/tubearchivist/es:/usr/share/elasticsearch/data
      # - ${DATA_DIR}/tubearchivist/es/snapshot:/usr/share/elasticsearch/data/snapshot
    healthcheck:
      test: "exit 0"
    depends_on:
      ts-tubearchivist:
        condition: service_healthy

# volumes:
#   media:
#   cache:
#   redis:
#   es:
#   tailscale:
#   tls:
